language: node_js
cache:
  yarn: true
  directories:
    - bin

sudo: required

services:
  - docker

before_install:
  - ./create-rpxc.sh
  - docker ps -a

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libudev-dev

env:
  global:
    - CC=gcc-4.9
    - CXX=g++-4.9

script:
  - ./build-image.sh

node_js:
  - 7
